In [1]:
import numpy as np

In [7]:
# Printing a Row Element of the Matrix
a = np.array([[7,8,9],[4,5,6],[1,2,3]])
print(a[0][1]) 

8


In [3]:
# Printing a Column of the Matrix
a = np.array([[7,8,9],[4,5,6],[1,2,3]])
print(a[:,1])   

[8 5 2]


In [8]:
# Matrix Addition
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[7,8,9],[4,5,6],[1,2,3]])
c = a+b
print(c)

[[ 8 10 12]
 [ 8 10 12]
 [ 8 10 12]]


In [9]:
# Matrix Multiplication 
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[7,8,9],[4,5,6],[1,2,3]])
c = a.dot(b)      
print(c)

[[ 18  24  30]
 [ 54  69  84]
 [ 90 114 138]]


In [10]:
# Transpose of a Matrix
a = np.array([[7,8,9],[4,5,6],[1,2,3]])
s = a.transpose()
print(s)

[[7 4 1]
 [8 5 2]
 [9 6 3]]
