# Numpy Function

In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
import numpy as np
import time
import sys
S= range(1000)
print(sys.getsizeof(5)*len(S))

D= np.arange(1000)
print(D.size*D.itemsize)

28000
4000


In [3]:
import time
import sys

SIZE = 1000000

L1= range(SIZE)
L2= range(SIZE)
A1= np.arange(SIZE)
A2=np.arange(SIZE)

start= time.time()
result=[(x,y) for x,y in zip(L1,L2)]
print((time.time()-start)*1000)

start=time.time()
result= A1+A2
print((time.time()-start)*1000)

472.8076457977295
144.42920684814453


In [4]:
import numpy as np
a = np.array([1,2,3,4])
print(a.itemsize)

4


In [5]:
import numpy as np
a = np.array([(1,2,3)])
print(a.dtype)

int32


In [6]:
import numpy as np
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


In [7]:
import numpy as np
a = np.array([(8,9,10),(11,12,13)])
print(a)
a=a.reshape(3,2)
print(a)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


In [8]:
import numpy as np
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0,2])

3


In [9]:
import numpy as np
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0:,2])

[3 5]


In [10]:
import numpy as np
a=np.array([(8,9),(10,11),(12,13)])
print(a[0:2,1])

[ 9 11]


In [11]:
import numpy as np
a= np.array([1,2,3])
print(a.min())
print(a.max())
print(a.sum())

1
3
6


In [12]:
import numpy as np
a= np.array([(1,2,3),(3,4,5)])
print(a.sum(axis=0))

[4 6 8]


In [21]:
import numpy as np
a=np.array([(1,2,3),(3,4,5,)])
print(np.sqrt(a))
print()
print(np.std(a))

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]

1.2909944487358056


In [14]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x+y)

[[ 2  4  6]
 [ 6  8 10]]


In [15]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x-y)
print()
print(x*y)
print()
print(x/y)

[[0 0 0]
 [0 0 0]]

[[ 1  4  9]
 [ 9 16 25]]

[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.vstack((x,y)))
print(np.hstack((x,y)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]
[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]


In [17]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
print(x.ravel())

[1 2 3 3 4 5]


In [18]:
import numpy as np
import matplotlib.pyplot as plt
a= np.array([1,2,3])
print(np.log(a))

[0.         0.69314718 1.09861229]


In [19]:
import numpy as np
import matplotlib.pyplot as plt
a= np.array([1,2,3])
print(np.log10(a))

[0.         0.30103    0.47712125]


In [20]:
import numpy as np
a= np.array([1,2,3])
print(np.exp(a))

[ 2.71828183  7.3890561  20.08553692]
